### PR TITLE
Remove discordjs-captcha dependency

### PR DESCRIPTION
**Pull request by nonsensetwice**
The `discord.js-captcha` dependency was responsible for the `node-pre-gyp` errors we have been seeing. Removing the dependency resolves this issue and allows for continued development.

### CODE REVIEW

**Review by okhaimie-dev — COMMENTED** [review]
Curious, why this package was installed but doesn't seem like it was even used in the first place.

I'll look through the code rq

**Review by okhaimie-dev — APPROVED** [review]
🐛

**Comment by nonsensetwice** [comment]
> Curious, why this package was installed but doesn't seem like it was even used in the first place.
> 
> I'll look through the code rq

@okhaimie-dev it was brought in when the First Quest features were baked into DEGEN way back in the day. This is a hold-over from when we split those features out into their own bot.

**Review by tikisailor — APPROVED** [review]

**Comment by tikisailor** [comment]
> 

Nice find!

**Pull request merged**
