### PR TITLE
Fix/notion guild urls update

### PR DESCRIPTION
**Pull request by okhaimie-dev**

### CODE REVIEW

**Review by nonsensetwice — APPROVED** [review]
Looks good! Thank you, @okhaimie-dev

**Comment by nonsensetwice** [comment]
@okhaimie-dev, please update this branch by selecting the "Update branch" button on this PR page and addressing any conflicts that may arise 🙏

**Review by LordRanchoatos — APPROVED** [review]
looks good!

**Comment by nonsensetwice** [comment]
Updated branch to include PR #80

**Pull request merged**
